language: shell

dist: xenial
sudo: false

stages:
  - "Lint"
  - "Unit test"
  - name: "Integration test"
    if: fork = false AND type = push
  - name: "GitHub release"
    if: fork = false AND type = push AND tag IS present

jobs:
  include:
    - stage: "Lint"
      script:
        - make lint

    - stage: "Unit test"
      script:
        - make test

    - stage: "Integration test"
      services:
        - docker
      addons:
        apt:
          packages:
            - pandoc
      env:
        secure: W+0Zmb13eZ9Gh+lD6DPCLHI7bqNoXNiFgWVcErdFuEJa5fjm61MXOjAGyHLe0Fr9OoBpcZbEdS7a5axzkrZN0eSvCjGoLHb9HOtjYNnkIyKrUCUCxyDFpJs1g9b0Euwlwyktch+5uXd8/3M+ltpLRcS5uCorL5ZUX2IkbaTmr+iM9q2y49khKSicAno+HBvVo+m1YBkvsyuhZZZGLXaN+O5hhio1xInHAJfKLgAqf2m0NWxM9A7Yk9lAUDG9m57eUsuNXwPtCkc/pdbUlhPWmdIkzwFrytOiLQeXI+J0WoXMjD+Fsr0gIcYIOb2H9mGd8AuixGEr0ZGbc0dHEcemb5HloEYqBR0C8T8EsYVa6njJZ3L0AZvLoPsPNEHoOFIQpuPykQeMf35i1qnpnAwFLElJEm1Ca/Yv+xlpBh22KPaAchSwlrwvLiHHxob/3EGSp3vLtg2Wz1rM/0OZqMYf2r/pSUBX770gFyFDqIAo1TLw33AhwwD1linkHq6ZB7GStegGqfAS/wvbMhiyz6JDxR2VHbamDpUZpdf5fF3TM1+g9NE1rRW5W4qlA2eUEP5a8OoWftEDzjAP1C9l74ovuMvXcHotBY2ll7LWb+mtct6SNSqWV45jEWi/yf2hSP+Fless6/5QMFBeIiTcnT+/aOkP5mcGHhKHfeyZjyZIeyc=
      before_script:
        - make dist
        - make -C integration-test image
      script:
        - make -C integration-test all

    - stage: "GitHub release"
      addons:
        apt:
          packages:
            - pandoc
      script:
        - make dist
      deploy:
        provider: releases
        api_key:
          secure: d5OiTAzExGVZwwrx+a4yLGgSl60rlMP++C06AfkSclmm67UrnTj6ysLJUVnB9hy0+NPIBxCtHc4oN9ctT8ihEC2unGx/ddD+D3m6yjYLJ5tX1hyqoznaN1k0skayBPWOdgpH30QWGQp0L9TXchc6GevAteukhtai8CCSQlHMJoDsjbVhPoO5tMMqlekcDfEuTWe4Xv8t3RKF4Rf5h4h9VZUg/6nI6rGgwbi1hEvqUfu7qyK6p37yVbhy3J+29oIQhBYrpYm2JVPCNDC7n72c269EPoOeA8Ni69hD9rhf3X5q4Ncvbm4a/lXYY9Mr0uOqmYgJYZPqCkL6S3VJSDPtpAGaU3FbSdkUQCQo7SYJtaLJ55SMpIMZ5eED5t3v18wdws8R0mxufqrcKhNV78y4/lgrbhj2bmwk7V9+LtDomT/TbpqHtHzINZHuFtBHpGCX1m3y6Lei/wmihqoMtNvYHGrve4jcpZvPtJ3WTLk/z1pRR4V77Kd0VsewkEOeL6Hlnso1atK5AWnNDnOKok49Z+Cqq0JlZKWAB1hyyHlD89ebPZNtOfzZPbhhRn3VWYwYBOm2dH1FzGniC57q1kUCh26m2pRGzDvtf2qTjMLMDQG0JxEd+Nz5AkrBXj4Go7xPfzoDBghUJC/kapUCJ03a3yvHVwAOWtCf239Svz26zuA=
        file:
          - dist/git-gau-src.tar.gz
          - dist/git-gau-dist.tar.gz
        skip_cleanup: true
        draft: true
        on:
          repo: znerol/git-gau
          tags: true
