language: shell

dist: xenial
sudo: false

stages:
  - "Lint"
  - "Unit test"
  - name: "Integration test"
    if: fork = false AND type = push
  - name: "GitHub release"
    if: fork = false AND type = push AND tag IS present

jobs:
  include:
    - stage: "Lint"
      script:
        - make lint

    - stage: "Unit test"
      script:
        - make test

    - stage: "Integration test"
      services:
        - docker
      addons:
        apt:
          packages:
            - pandoc
      env:
        secure: p0lNS3poxL2TJ05dSgY1FDD4W7flE6DlaXFQFi8bISb0onkb+r16E+XgYGx6b5T4tQt212fJjgTMm768aLS+JRZFSXIFpV3+arYGzu22pqCweMrEJ3D9ku+1otDBEuHB45Xyb9/gdv9Qf0Pgs9z+B6Blg2w0k3y/RnH84N2PC1L4jbOU9DU6kE7Ez24yYl+NI7YRJ5BBB73ortdsU7Okkvwp1580hVVA/uv5OHQjLam2WTBOAVpqJDclV8dXIO2NG+EqMYPOuJmK3dML/RGyROSTbsw29avlr2gV8ehQGKxQFRUFCoyxolTN/qKGsfhnITzXnQyU7+03uqNkRxqCq1Jx1zxPjA+i2pA1gEBzdA0Q4Ju4/KHETMXVX3ZwEc374xHh+umhmglxw/4gOVRf5sHiZKmEOUSaiBY1HBDwHpvwtBl1PUC+6b6WzLhJn99JSNqA3l2n1a9Y4+KG4Dn5wQPj9VfoLUL2FUBgQud9d330hvh3wncWVHYJVNtk+0FNOGex0bN1FCwzUwPHey1WGrYVfnErZ7txD08X5mPovuDfv3RwgIc9SxdMlTbHmkIe1/cDflLHvpDX46Wd5MWTAixnp+YC8Agqpulh6MtZVhRcP+KGb36TwvowWbshoPniPdg2Swu8yvtuAmOEwS3Ah6037hKW6p+H0eJ36AiZeZs=
      before_script:
        - make dist
        - make -C integration-test image
      script:
        - make -C integration-test all

    - stage: "GitHub release"
      addons:
        apt:
          packages:
            - pandoc
      script:
        - make dist
      deploy:
        provider: releases
        api_key:
          secure: d5OiTAzExGVZwwrx+a4yLGgSl60rlMP++C06AfkSclmm67UrnTj6ysLJUVnB9hy0+NPIBxCtHc4oN9ctT8ihEC2unGx/ddD+D3m6yjYLJ5tX1hyqoznaN1k0skayBPWOdgpH30QWGQp0L9TXchc6GevAteukhtai8CCSQlHMJoDsjbVhPoO5tMMqlekcDfEuTWe4Xv8t3RKF4Rf5h4h9VZUg/6nI6rGgwbi1hEvqUfu7qyK6p37yVbhy3J+29oIQhBYrpYm2JVPCNDC7n72c269EPoOeA8Ni69hD9rhf3X5q4Ncvbm4a/lXYY9Mr0uOqmYgJYZPqCkL6S3VJSDPtpAGaU3FbSdkUQCQo7SYJtaLJ55SMpIMZ5eED5t3v18wdws8R0mxufqrcKhNV78y4/lgrbhj2bmwk7V9+LtDomT/TbpqHtHzINZHuFtBHpGCX1m3y6Lei/wmihqoMtNvYHGrve4jcpZvPtJ3WTLk/z1pRR4V77Kd0VsewkEOeL6Hlnso1atK5AWnNDnOKok49Z+Cqq0JlZKWAB1hyyHlD89ebPZNtOfzZPbhhRn3VWYwYBOm2dH1FzGniC57q1kUCh26m2pRGzDvtf2qTjMLMDQG0JxEd+Nz5AkrBXj4Go7xPfzoDBghUJC/kapUCJ03a3yvHVwAOWtCf239Svz26zuA=
        file:
          - dist/git-gau-src.tar.gz
          - dist/git-gau-dist.tar.gz
        skip_cleanup: true
        draft: true
        on:
          repo: znerol/git-gau
          tags: true
