#!/bin/sh

set -e
set -u

ECHO=/bin/echo

GAU_GIT_CREDENTIALS="${GAU_GIT_CREDENTIALS:-}"
GAU_GIT_CREDENTIALS_FILE="${GAU_GIT_CREDENTIALS_FILE:-${HOME}/.git-credentials}"

# Optionally write git credentials file.
if [ -n "${GAU_GIT_CREDENTIALS}" ]; then
    if [ ! -e "${GAU_GIT_CREDENTIALS_FILE}" ]; then
        (umask 077 && ${ECHO} "${GAU_GIT_CREDENTIALS}" > "${GAU_GIT_CREDENTIALS_FILE}")
    fi
fi
