#!/bin/sh

set -e
set -u

ECHO=/bin/echo
INSTALL=/usr/bin/install

GAU_GIT_CREDENTIALS="${GAU_GIT_CREDENTIALS:-}"
GAU_GIT_CREDENTIALS_FILE="${GAU_GIT_CREDENTIALS_FILE:-${HOME}/.git-credentials}"
GAU_GIT_CREDENTIALS_SRC_FILE="${GAU_GIT_CREDENTIALS_SRC_FILE:-}"

# Optionally write git credentials file.
if [ -n "${GAU_GIT_CREDENTIALS}" ]; then
    if [ ! -e "${GAU_GIT_CREDENTIALS_FILE}" ]; then
        (umask 077 && ${ECHO} "${GAU_GIT_CREDENTIALS}" > "${GAU_GIT_CREDENTIALS_FILE}")
    fi
fi

# Optionally copy git credentials file.
if [ -n "${GAU_GIT_CREDENTIALS_SRC_FILE}" ]; then
    if [ ! -e "${GAU_GIT_CREDENTIALS_FILE}" ]; then
        ${INSTALL} -m 0600 "${GAU_GIT_CREDENTIALS_SRC_FILE}" "${GAU_GIT_CREDENTIALS_FILE}"
    fi
fi
