#!/bin/sh

set -e
set -u

ECHO=/bin/echo
INSTALL=/usr/bin/install

GAU_SSH_DIR="${GAU_SSH_DIR:-${HOME}/.ssh}"
GAU_SSH_KNOWNHOSTS="${GAU_SSH_KNOWNHOSTS:-}"
GAU_SSH_KNOWNHOSTS_FILE="${GAU_SSH_KNOWNHOSTS_FILE:-${GAU_SSH_DIR}/known_hosts}"
GAU_SSH_KNOWNHOSTS_SRC_FILE="${GAU_SSH_KNOWNHOSTS_SRC_FILE:-}"

# Optionally setup the SSH known hosts file.
if [ -n "${GAU_SSH_KNOWNHOSTS}" ]; then
    ${INSTALL} -m 0700 -d "${GAU_SSH_DIR}"
    if [ ! -e "${GAU_SSH_KNOWNHOSTS_FILE}" ]; then
        ${ECHO} "${GAU_SSH_KNOWNHOSTS}" > "${GAU_SSH_KNOWNHOSTS_FILE}"
    fi
fi

# Optionally copy the SSH known hosts file.
if [ -n "${GAU_SSH_KNOWNHOSTS_SRC_FILE}" ]; then
    ${INSTALL} -m 0700 -d "${GAU_SSH_DIR}"
    if [ ! -e "${GAU_SSH_KNOWNHOSTS_FILE}" ]; then
        ${INSTALL} -m 0644 "${GAU_SSH_KNOWNHOSTS_SRC_FILE}" "${GAU_SSH_KNOWNHOSTS_FILE}"
    fi
fi
