#!/bin/sh

set -e
set -u

ECHO=/bin/echo
INSTALL=/usr/bin/install
SSH_ADD=/usr/bin/ssh-add

GAU_SSH_DIR="${GAU_SSH_DIR:-${HOME}/.ssh}"
GAU_SSH_PRIVKEY="${GAU_SSH_PRIVKEY:-}"
GAU_SSH_PRIVKEY_FILE="${GAU_SSH_PRIVKEY_FILE:-${GAU_SSH_DIR}/id_rsa}"
GAU_SSH_PRIVKEY_SRC_FILE="${GAU_SSH_PRIVKEY_SRC_FILE:-}"

# Optionally write an SSH private key file.
if [ -n "${GAU_SSH_PRIVKEY}" ]; then
    ${INSTALL} -m 0700 -d "${GAU_SSH_DIR}"
    if [ ! -e "${GAU_SSH_PRIVKEY_FILE}" ]; then
        (umask 077 && ${ECHO} "${GAU_SSH_PRIVKEY}" > "${GAU_SSH_PRIVKEY_FILE}")
    fi
fi

# Optionally copy an SSH private key file.
if [ -n "${GAU_SSH_PRIVKEY_SRC_FILE}" ]; then
    ${INSTALL} -m 0700 -d "${GAU_SSH_DIR}"
    if [ ! -e "${GAU_SSH_PRIVKEY_FILE}" ]; then
        ${INSTALL} -m 0600 "${GAU_SSH_PRIVKEY_SRC_FILE}" "${GAU_SSH_PRIVKEY_FILE}"
    fi
fi

# Optionally add an SSH private key file into the agent.
if [ -n "${SSH_AGENT_PID:-}" ] && [ -e "${GAU_SSH_PRIVKEY_FILE}" ]; then
    ${SSH_ADD} "${GAU_SSH_PRIVKEY_FILE}"
fi
